<?php

declare(strict_types=1);

namespace Pramnos\Tests\Unit\Pramnos\Document;

use PHPUnit\Framework\TestCase;
use Pramnos\Document\Document;
use Pramnos\Document\DocumentTypes\Html;
use Pramnos\Framework\Factory;
use Pramnos\Http\Request;

/**
 * A signed-in page carries the token its own JavaScript needs to call its own API.
 *
 * The three parts of a same-origin API call were each correct and could not talk to
 * each other: `ApiAuthMiddleware` accepts a session plus an `X-CSRF-Token` header,
 * `pf-utils.js` sends that header from `<meta name="csrf">`, and no document ever
 * printed the tag. What that looked like was the framework's own search box
 * rendering, the endpoint answering, and typing doing nothing — a 403 in the console
 * and nothing on the page.
 *
 * Asserted in both directions, because "prints a token" alone would pass on a
 * document that prints one for anonymous visitors too. That is the more expensive
 * mistake of the two: reading the token starts a session, and a public URL that
 * starts a session is a page no shared cache can hold.
 */
class CsrfMetaReachesTheHeadTest extends TestCase
{
    protected function setUp(): void
    {
        if (!class_exists('pramnos_request')) {
            class_alias(Request::class, 'pramnos_request');
        }

        Factory::getLanguage()->addlang([
            'LangShort' => 'en',
            'CHARSET'   => 'UTF-8',
        ]);

        Request::$originalRequestNoChange = '/a-page';
        Document::_setContent('');

        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }
        unset($_SESSION['usertoken'], $_SESSION['csrf_token']);
    }

    protected function tearDown(): void
    {
        Document::_setContent('');
        unset($_SESSION['usertoken'], $_SESSION['csrf_token']);
    }

    /**
     * With a web session in place, the head carries the session's CSRF token.
     */
    public function testASignedInPageCarriesTheToken(): void
    {
        // Arrange — a session as the login path leaves it
        $token            = new \Pramnos\User\Token();
        $token->tokentype = \Pramnos\User\Token::TYPE_WEB_SESSION;
        $token->status    = 1;
        $_SESSION['usertoken']  = $token;
        $_SESSION['csrf_token'] = 'a1b2c3d4';

        // Act
        $output = (new Html())->render();

        // Assert
        $this->assertStringContainsString(
            '<meta name="csrf" content="a1b2c3d4" />',
            $output,
            'the tag pf-utils.js reads must be on the page'
        );
    }

    /**
     * An anonymous page carries no token — and is not given a session to hold one.
     */
    public function testAnAnonymousPageCarriesNoTokenAndGeneratesNone(): void
    {
        // Arrange — no web-session token in the session

        // Act
        $output = (new Html())->render();

        // Assert
        $this->assertStringNotContainsString('name="csrf"', $output);
        $this->assertArrayNotHasKey(
            'csrf_token',
            $_SESSION,
            'rendering a public page must not mint a token: that write is what makes '
            . 'the page uncacheable'
        );
    }

    /**
     * The token is escaped like every other head value.
     *
     * It is generated by `random_bytes()` and cannot contain a quote today — which is
     * exactly the reasoning that leaves an unescaped concatenation in place until the
     * day something else writes `$_SESSION['csrf_token']`.
     */
    public function testTheTokenIsEscaped(): void
    {
        // Arrange
        $token            = new \Pramnos\User\Token();
        $token->tokentype = \Pramnos\User\Token::TYPE_WEB_SESSION;
        $token->status    = 1;
        $_SESSION['usertoken']  = $token;
        $_SESSION['csrf_token'] = 'a" onload="alert(1)';

        // Act
        $output = (new Html())->render();

        // Assert
        $this->assertStringNotContainsString('onload="alert(1)"', $output);
        $this->assertStringContainsString('&quot; onload=', $output);
    }
}
