<?php

namespace Pramnos\Tests\Integration\User;

use PHPUnit\Framework\TestCase;
use Pramnos\Database\Database;
use Pramnos\User\User;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\Attributes\Test;

#[CoversClass(User::class)]
class UserTest extends TestCase
{
    private $db;
    private $testUsername = 'testuser_' . 42; // Constant for deterministic tests if needed, or random
    
    protected function setUp(): void
    {
        // Define CONFIG path if not set, pointing to our test fixtures
        if (!\defined('CONFIG')) {
            \define('CONFIG', 'tests' . \DS . 'fixtures' . \DS . 'app');
        }

        // Explicitly load test settings
        $settingsFile = \ROOT . \DS . 'tests' . \DS . 'fixtures' . \DS . 'app' . \DS . 'settings.php';
        \Pramnos\Application\Settings::loadSettings($settingsFile);
        \Pramnos\Application\Application::getInstance();

        $this->db = \Pramnos\Framework\Factory::getDatabase();
        if (!$this->db->connected) {
            $this->db->connect();
        }

        // Clear Guest user to ensure seeding logic in setupDb triggers predictably
        $userTable = defined('DB_USERSTABLE') ? DB_USERSTABLE : '#PREFIX#users';
        $this->db->query("DELETE FROM " . $userTable . " WHERE userid = 1");

        \Pramnos\User\User::setupDb();

        $this->testUsername = 'testuser_' . \bin2hex(\random_bytes(4));
    }

    #[Test]
    public function testUserLifecycleOnCurrentDatabase()
    {
        $db = $this->db;
        
        // 1. Create User
        $user = new User();
        $user->username = $this->testUsername;
        $user->email = $this->testUsername . '@example.com';
        $user->setPassword('secret123');
        $user->firstname = 'Test';
        $user->lastname = 'User';
        
        // Set some metadata (otherinfo)
        $user->setinfo_my_custom_field = 'custom_value';
        $user->setinfo_another_field = 123;
        
        $user->save();
        $userId = $user->userid;
        
        $this->assertGreaterThan(1, $userId, "User ID should be greater than 1 after save");
        
        // 2. Load User and verify metadata
        $loadedUser = new User($userId);
        $this->assertEquals($this->testUsername, $loadedUser->username);
        $this->assertEquals('custom_value', $loadedUser->getinfo_my_custom_field);
        $this->assertEquals(123, $loadedUser->getinfo_another_field);
        
        // 3. Update metadata (testing UPSERT)
        $loadedUser->setinfo_my_custom_field = 'updated_value';
        $loadedUser->setinfo_new_field = 'brand_new';
        $loadedUser->save();
        
        $reLoadedUser = new User($userId);
        $this->assertEquals('updated_value', $reLoadedUser->getinfo_my_custom_field);
        $this->assertEquals('brand_new', $reLoadedUser->getinfo_new_field);
        
        // 4. Test Activation/Deactivation (testing convertBool)
        $reLoadedUser->activate();
        // Since activate() saves immediately in User.php implementation
        $checkUser = new User($userId);
        $this->assertTrue((bool)$checkUser->active, "User should be active");
        
        $checkUser->deactivate();
        $checkUserAgain = new User($userId);
        $this->assertFalse((bool)$checkUserAgain->active, "User should be inactive");
        
        // 5. Cleanup
        $checkUserAgain->deleteuser();
        $finalCheck = new User($userId);
        // User::load returns false if not found
        $this->assertFalse($finalCheck->load($userId), "User should be deleted");
    }

    #[Test]
    public function testUserOperationsOnPostgreSQL()
    {
        $pgSettings = \Pramnos\Application\Settings::getSetting('postgresql');
        if (!$pgSettings) {
             $this->markTestSkipped('PostgreSQL settings not found');
        }

        $db = new Database();
        $db->type = 'postgresql';
        $db->server = $pgSettings->hostname;
        $db->user = $pgSettings->user;
        $db->password = $pgSettings->password;
        $db->database = $pgSettings->database;
        $db->port = $pgSettings->port;
        $db->schema = $pgSettings->schema ?? 'public';
        
        if (!$db->connect(false)) {
            $this->markTestSkipped('PostgreSQL container not reachable');
        }
        
        // Ensure we can run a simple query
        $result = $db->query("SELECT 1 as connected");
        $this->assertEquals(1, $result->numRows);
    }
    
    private function runCrossDriverTest($db)
    {
        // This is a manual test of the User logic with a specific DB connection
        // Note: User class uses Factory::getDatabase() internally in many methods.
        // To properly test, we'd need to mock the Factory or the Database.
        // But our goal is to ensure the SQL generated by Database handles the dialects.
        
        $this->assertTrue(true); // Placeholder for complex Mocking if needed
    }
}
