
services:
  php-apache-environment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pramnos_php
    ports:
      - "18081:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=timescaledb
      - DB_USER=postgres
      - DB_PASS=secret
      - DB_NAME=pramnos_test
      - DB_TYPE=postgresql
      - CACHE_HOST=redis
    depends_on:
      - db
      - timescaledb
      - redis

  db:
    image: mysql:8.0
    container_name: pramnos_db
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=pramnos_test
    ports:
      - "3306"

  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: pramnos_timescaledb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=pramnos_test
    ports:
      - "5432"

  redis:
    image: redis:alpine
    container_name: pramnos_redis
    ports:
      - "6379"
