<?php

namespace Pramnos\Framework\Migrations\Auth;

use Pramnos\Database\Migration;

/**
 * Creates the twofactor_setup table — temporary session tokens for the 2FA setup flow.
 *
 * Each row represents one in-progress setup attempt. The session is valid for
 * 15 minutes (expires_at = created_at + 900). The row is marked used=1 when
 * completeSetup() succeeds; cleanupExpiredSessions() removes expired/used rows.
 *
 * @package PramnosFramework
 */
class CreateTwofactorSetupTable extends Migration
{
    public string  $feature      = 'auth';
    public string  $scope        = 'framework';
    public int     $priority     = 85;
    public array   $dependencies = [];
    public $description  = 'Creates the twofactor_setup temporary setup session table';

    public function up(): void
    {
        $schema = $this->application->database->schema();

        if ($schema->hasTable('twofactor_setup')) {
            return;
        }

        $schema->createTable('twofactor_setup', function ($table) {
            $table->comment('Temporary 2FA setup sessions — 15-minute TTL; used=1 once completeSetup() succeeds');

            $table->increments('id')
                ->comment('Auto-increment session identifier');
            $table->bigInteger('userid')
                ->comment('User ID initiating the setup');
            $table->string('temp_secret', 64)
                ->comment('Ephemeral base32 TOTP secret generated by startSetup(); stored until confirmed');
            $table->tinyInteger('used')->default(0)
                ->comment('1 = setup completed and this session consumed; 0 = still valid');
            $table->integer('expires_at')
                ->comment('Unix timestamp after which this session is invalid (created_at + 900 s)');
            $table->integer('created_at')
                ->comment('Unix timestamp when this setup session was created');

            $table->index(['userid', 'used'], 'idx_twofactor_setup_userid_used');
            $table->index(['expires_at'], 'idx_twofactor_setup_expires');
        });
    }

    public function down(): void
    {
        $this->application->database->schema()->dropTableIfExists('twofactor_setup');
    }
}
