<?php

namespace Pramnos\Routing;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-19 at 15:27:13.
 */
#[\PHPUnit\Framework\Attributes\CoversClass(\Pramnos\Routing\Route::class)]
#[\PHPUnit\Framework\Attributes\IgnoreDeprecations]
class RouteTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Route
     */
    protected $route;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->route = new Route('/foo/bar', 'POST', function(){return 'ab';});
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {
        $this->route = null;
    }

    
    public function testConstruct()
    {
        $route = new Route('/foo/bar', 'post', function(){});
        $this->assertInstanceOf('\Pramnos\Routing\Route', $route);
    }

    
    public function testMatch()
    {
        $this->assertTrue(
            $this->route->matches(
                \Pramnos\Http\Request::create('/foo/bar', 'post')
            )
        );
    }

    
    public function testParameters()
    {
        $route = new Route(
            'foo/{name}/boom/{age?}/{location?}', 'GET', function(){}
        );
        $this->assertTrue(
            $route->matches(
                \Pramnos\Http\Request::create('foo/Yannis/boom/30', 'GET')
            )
        );
    }

    
    public function testNoMatch()
    {
        $this->assertFalse(
            $this->route->matches(
                \Pramnos\Http\Request::create('/foo/nofound', 'POST')
            )
        );
    }

    
    public function testNoMatchMethod()
    {
        $this->assertFalse(
            $this->route->matches(
                \Pramnos\Http\Request::create('/foo/bar', 'get')
            )
        );
    }

    
    public function testExecution()
    {
        $route = new Route(
            'foo/{name}/boom/{age?}/{location?}', 'GET',
            function ($name, $age = 25, $location = 'GR') {
                return $name.$age.$location;
            }
        );
        $this->assertTrue(
            $route->matches(
                \Pramnos\Http\Request::create('foo/Yannis/boom/30', 'GET')
            )
        );
        $this->assertEquals(
            'Yannis30GR',
            $route->execute(
                new \Pramnos\Application\Application('myApp')
            )
        );
    }

    
    public function testNotCallableExecution()
    {
        $route = new Route(
            'foo/{name}/boom/{age?}/{location?}', 'GET',
            'test'
        );
        $this->assertTrue(
            $route->matches(
                \Pramnos\Http\Request::create('foo/Yannis/boom/30', 'GET')
            )
        );
        $this->assertNull(
            $route->execute(
                new \Pramnos\Application\Application('myApp')
            )
        );
    }

    /**
     * A [class-string, method] action with a NON-STATIC method (the shape
     * attribute routing produces) must instantiate the controller and invoke the
     * method with matched URI parameters injected by name. This previously did
     * nothing (is_callable() was false for an instance method), so it is the
     * regression guard for the Route::execute() fix.
     */
    public function testExecutionWithNonStaticControllerAction()
    {
        $route = new Route('users/{name}', 'GET', [RouteTestController::class, 'show']);
        $this->assertTrue(
            $route->matches(\Pramnos\Http\Request::create('users/Yannis', 'GET'))
        );
        // name matched, age falls back to the method default.
        $this->assertSame(
            'show:Yannis:25',
            $route->execute(new \Pramnos\Application\Application('myApp'))
        );
    }

    /**
     * A [class-string, method] action with a STATIC method also dispatches (it
     * previously threw a TypeError from ReflectionFunction on the array).
     */
    public function testExecutionWithStaticControllerAction()
    {
        $route = new Route('s/{name}', 'GET', [RouteTestController::class, 'stat']);
        $this->assertTrue(
            $route->matches(\Pramnos\Http\Request::create('s/Bob', 'GET'))
        );
        $this->assertSame(
            'stat:Bob',
            $route->execute(new \Pramnos\Application\Application('myApp'))
        );
    }
}

/**
 * Fixture controller for the [class, method] action tests above.
 */
class RouteTestController
{
    public function show($name, $age = 25)
    {
        return "show:{$name}:{$age}";
    }

    public static function stat($name)
    {
        return "stat:{$name}";
    }
}
