<?php

declare(strict_types=1);

namespace Pramnos\Tests\Unit\Pramnos\Email;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Pramnos\Email\Email;
use Symfony\Component\Mime\Email as MimeEmail;

/**
 * The headers that decide how a mailbox provider treats a message.
 *
 * None of them changes what the reader sees, and all of them change what happens to the
 * message — which is why they go missing: nothing reports a missing header back to the sender,
 * and nothing reports a malformed one either. `List-Unsubscribe` was emitted without its angle
 * brackets for a long time on that basis: present, plausible in a dump, ignored by every
 * provider.
 */
#[CoversClass(Email::class)]
class DeliverabilityHeadersTest extends TestCase
{
    /**
     * The headers a message would carry, as `name => value`.
     *
     * @param array<string, mixed> $properties Public properties to set on the sender
     * @return array<string, string>
     */
    private function headersFor(array $properties = []): array
    {
        $sender = new class extends Email {
            public function apply(MimeEmail $email): void
            {
                $this->addDeliverabilityHeaders($email);
            }
        };

        foreach ($properties as $name => $value) {
            $sender->$name = $value;
        }

        $mime = new MimeEmail();
        $sender->apply($mime);

        $headers = [];

        foreach ($mime->getHeaders()->all() as $header) {
            $headers[$header->getName()] = $header->getBodyAsString();
        }

        return $headers;
    }

    /**
     * Every message says it was generated by a program.
     *
     * RFC 3834. It is what stops an out-of-office responder replying to a password reset — and
     * then to the reply, which is how a mail loop starts. The header most often missing from
     * transactional mail, and the cheapest to add.
     */
    public function testEveryMessageIsMarkedAutoGenerated(): void
    {
        // Act
        $headers = $this->headersFor();

        // Assert
        $this->assertSame('auto-generated', $headers['Auto-Submitted']);
    }

    /**
     * Every message carries a unique reference, so Gmail does not collapse two into one.
     *
     * Gmail groups by subject, and this framework's most useful mail has a repeating subject —
     * «a new sign-in to your account». Two sign-ins from two devices arrived as one message with
     * the older hidden behind "show trimmed content", which is exactly the message somebody
     * needs to see twice.
     */
    public function testEachMessageHasItsOwnReference(): void
    {
        // Act
        $first  = $this->headersFor();
        $second = $this->headersFor();

        // Assert
        $this->assertNotSame(
            $first['X-Entity-Ref-ID'],
            $second['X-Entity-Ref-ID'],
            'two messages sharing a reference is the collapse this prevents'
        );
        $this->assertMatchesRegularExpression('~^[0-9a-f]{32}$~', $first['X-Entity-Ref-ID']);
    }

    /**
     * Transactional mail gets none of the bulk headers.
     *
     * Marking a password reset `Precedence: bulk` invites a provider to deprioritise the one
     * message the reader is waiting for, and a `List-ID` on mail that belongs to no list is a
     * stable identifier for something that does not exist.
     */
    public function testTransactionalMailIsNotMarkedAsBulk(): void
    {
        // Act — no unsubscribeList means transactional
        $headers = $this->headersFor(['from' => 'noreply@example.com']);

        // Assert
        $this->assertArrayNotHasKey('Precedence', $headers);
        $this->assertArrayNotHasKey('List-ID', $headers);
        $this->assertArrayNotHasKey('Feedback-ID', $headers);
    }

    /**
     * List mail gets `Precedence`, `List-ID` and `Feedback-ID`.
     *
     * `Feedback-ID` is Google Postmaster's grouping key: without it every complaint about every
     * message lands in one bucket, and the dashboard can say that something is wrong but not
     * what. With it, «the newsletter is being marked as spam and the receipts are not» becomes a
     * fact rather than a theory.
     */
    public function testListMailIsIdentifiedAsSuch(): void
    {
        // Act
        $headers = $this->headersFor([
            'from'            => 'news@example.com',
            'unsubscribeList' => 'newsletter',
        ]);

        // Assert
        $this->assertSame('bulk', $headers['Precedence']);
        $this->assertSame('<newsletter.example.com>', $headers['List-ID']);
        $this->assertSame('newsletter:pramnos:bulk:example.com', $headers['Feedback-ID']);
    }

    /**
     * A list name with characters those headers reject is reduced, not passed through.
     *
     * `Feedback-ID` accepts letters, digits, `_`, `.` and `-`, and one bad character or one
     * over-long field invalidates the whole header — silently, and nowhere near the sender.
     */
    public function testAnAwkwardListNameIsReducedToWhatTheHeaderAllows(): void
    {
        // Act
        $headers = $this->headersFor([
            'from'            => 'news@example.com',
            'unsubscribeList' => 'Νέα & προσφορές!',
        ]);

        // Assert
        $this->assertMatchesRegularExpression(
            '~^[A-Za-z0-9_.:-]+$~',
            $headers['Feedback-ID'],
            'only the characters Google accepts'
        );

        foreach (explode(':', $headers['Feedback-ID']) as $field) {
            $this->assertLessThanOrEqual(64, strlen($field));
        }
    }

    /**
     * The host comes from the sender address, and falls back to the site URL.
     *
     * A `List-ID` built on the wrong domain is worse than none.
     */
    public function testTheHostComesFromTheSenderAddress(): void
    {
        // Act
        $headers = $this->headersFor([
            'from'            => 'Newsletter <news@mail.example.org>',
            'unsubscribeList' => 'weekly',
        ]);

        // Assert
        $this->assertSame('<weekly.mail.example.org>', $headers['List-ID']);
    }

    /**
     * With no host to be found, the bulk identifiers are left out rather than invented.
     */
    public function testWithoutAHostTheIdentifiersAreOmitted(): void
    {
        // Act — no from address, and no site URL in this test environment
        $headers = $this->headersFor(['unsubscribeList' => 'weekly']);

        // Assert
        $this->assertSame('bulk', $headers['Precedence'], 'this one needs no host');
        $this->assertArrayNotHasKey('List-ID', $headers);
        $this->assertArrayNotHasKey('Feedback-ID', $headers);
    }

    /**
     * A caller that set a header itself keeps it.
     *
     * These are defaults, not policy. An application with its own `Feedback-ID` scheme — one
     * that distinguishes campaigns, which is the whole point of the header — must not have it
     * overwritten by a generic one.
     */
    public function testAnExplicitHeaderWins(): void
    {
        // Act
        $headers = $this->headersFor([
            'from'            => 'news@example.com',
            'unsubscribeList' => 'newsletter',
            'headers'         => [
                'Feedback-ID'     => 'spring-sale:campaigns:bulk:example.com',
                'auto-submitted'  => 'auto-replied',
            ],
        ]);

        // Assert — neither default was added, and the caller's own are applied elsewhere
        $this->assertArrayNotHasKey('Feedback-ID', $headers);
        $this->assertArrayNotHasKey('Auto-Submitted', $headers);
        $this->assertSame('bulk', $headers['Precedence'], 'the ones not overridden still apply');
    }
}
