<?php

declare(strict_types=1);

namespace Tests\Unit\Pramnos\Console\Make;

use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;
use Pramnos\Console\Commands\Make\MakeWebhook;
use Symfony\Component\Console\Input\ArrayInput;
use Symfony\Component\Console\Output\BufferedOutput;

/**
 * Unit tests for the project:git-webhook command.
 *
 * The command writes ROOT/www/webhook.php and optionally appends
 * WEBHOOK_SECRET to ROOT/.env.example. Tests run against the real project
 * ROOT (the framework checkout) so tearDown removes every artifact:
 * www/webhook.php is deleted and .env.example is only created by the test
 * that needs it (and removed afterwards).
 *
 * Covered paths:
 *  - fresh generation (file did not exist) → exit 0, stub content
 *  - existing file without --force → exit 1, file untouched
 *  - existing file with --force → exit 0, overwritten
 *  - --branch option propagated into the generated script
 *  - .env.example append branch (key absent → appended, present → skipped)
 *  - detectCliName() fallback to 'pramnos' when no app.php / root php file
 */
#[CoversClass(MakeWebhook::class)]
class MakeWebhookTest extends TestCase
{
    private string $target;
    private string $envExample;

    protected function setUp(): void
    {
        $this->target     = ROOT . '/www/webhook.php';
        $this->envExample = ROOT . '/.env.example';

        // Pre-condition: neither artifact may exist before a test runs.
        @unlink($this->target);
        @unlink($this->envExample);
    }

    protected function tearDown(): void
    {
        // Always remove generated artifacts so the repo stays clean.
        @unlink($this->target);
        @unlink($this->envExample);
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Execute project:git-webhook with the given CLI parameters and return
     * [exitCode, display output].
     *
     * execute() is protected on Symfony commands, so it is invoked through
     * reflection after binding an ArrayInput against the command definition.
     *
     * @param array<string, mixed> $params e.g. ['--force' => true]
     * @return array{0:int, 1:string}
     */
    private function runCommand(array $params = []): array
    {
        $command = new MakeWebhook();
        $input   = new ArrayInput($params, $command->getDefinition());
        $output  = new BufferedOutput();

        $ref = new \ReflectionMethod($command, 'execute');
        $exit = $ref->invoke($command, $input, $output);

        return [$exit, $output->fetch()];
    }

    /**
     * A stray PHP file in the project root does not become the CLI name.
     *
     * `detectCliName()` used to take the first `*.php` in the root that was not one of
     * three excluded names — a blocklist, which has to enumerate everything that is
     * *not* the answer. It was wrong the first time somebody left a file there: a
     * `demo.php` committed to this repository made the generator emit
     * `Generated by: php demo project:git-webhook`, an instruction that is written
     * down, looks authoritative, and does not work.
     *
     * A console entry point constructs the application's `Console` and runs it. This
     * test plants a file that does neither and requires the fallback to hold.
     *
     * @return void
     */
    public function testAStrayRootScriptIsNotMistakenForTheCli(): void
    {
        // Arrange — a plausible stray: a scratch script, alphabetically early
        $stray = ROOT . '/aaa-scratch-' . bin2hex(random_bytes(4)) . '.php';
        file_put_contents($stray, "<?php\n// scratch\necho 'hello';\n");

        try {
            // Act
            [$exit, ] = $this->runCommand();
            $generated = (string) file_get_contents($this->target);

            // Assert
            $this->assertSame(0, $exit);
            $this->assertStringContainsString(
                'php pramnos project:git-webhook',
                $generated,
                'A file that is not a console entry point must not name the CLI.'
            );
            $this->assertStringNotContainsString(basename($stray, '.php'), $generated);
        } finally {
            @unlink($stray);
        }
    }

    /**
     * A real console entry point is recognised.
     *
     * The other half: identifying positively is only an improvement if it still
     * identifies. A scaffolded entry point constructs the Console and runs it.
     *
     * @return void
     */
    public function testARealEntryPointIsRecognised(): void
    {
        // Arrange
        $cli = ROOT . '/myapp.php';
        file_put_contents(
            $cli,
            "<?php\n\$consoleApp = new \\MyApp\\Console('MyApp CLI');\n\$consoleApp->run();\n"
        );

        try {
            // Act
            $this->runCommand();
            $generated = (string) file_get_contents($this->target);

            // Assert
            $this->assertStringContainsString('php myapp project:git-webhook', $generated);
        } finally {
            @unlink($cli);
        }
    }

    // =========================================================================
    // Fresh generation
    // =========================================================================

    /**
     * Running project:git-webhook when www/webhook.php does not exist must create the
     * file with the standard stub (WebhookHandler bootstrap, default branch
     * 'main', fallback CLI name 'pramnos') and exit 0.
     */
    public function testCreatesWebhookScriptWithDefaults(): void
    {
        // Arrange — setUp removed any pre-existing file.

        // Act
        [$exit, $out] = $this->runCommand();

        // Assert — success exit and confirmation message
        $this->assertSame(0, $exit);
        $this->assertStringContainsString('Created www/webhook.php', $out);
        $this->assertFileExists($this->target);

        $content = (string) file_get_contents($this->target);
        // The stub must bootstrap the WebhookHandler
        $this->assertStringContainsString('WebhookHandler', $content);
        $this->assertStringContainsString('WEBHOOK_SECRET', $content);
        // Default branch is main
        $this->assertStringContainsString("onBranch('main'", $content);
        $this->assertStringContainsString('git reset --hard origin/main', $content);
        // No app.php / root entry script in this project → 'pramnos' fallback
        $this->assertStringContainsString('php pramnos migrate', $content);
    }

    /**
     * The --branch option must replace 'main' in every generated command
     * sequence (onBranch target and the git reset line).
     */
    public function testBranchOptionIsPropagated(): void
    {
        // Arrange / Act
        [$exit] = $this->runCommand(['--branch' => 'develop']);

        // Assert
        $this->assertSame(0, $exit);
        $content = (string) file_get_contents($this->target);
        $this->assertStringContainsString("onBranch('develop'", $content);
        $this->assertStringContainsString('git reset --hard origin/develop', $content);
    }

    // =========================================================================
    // Overwrite protection
    // =========================================================================

    /**
     * When www/webhook.php already exists and --force is not given, the
     * command must refuse to overwrite it and exit 1.
     */
    public function testExistingFileWithoutForceFails(): void
    {
        // Arrange — pre-create a sentinel file
        file_put_contents($this->target, 'SENTINEL');

        // Act
        [$exit, $out] = $this->runCommand();

        // Assert — exit 1, warning printed, file untouched
        $this->assertSame(1, $exit);
        $this->assertStringContainsString('already exists', $out);
        $this->assertSame('SENTINEL', file_get_contents($this->target),
            'Existing file must not be overwritten without --force');
    }

    /**
     * --force must overwrite an existing www/webhook.php and exit 0.
     */
    public function testForceOverwritesExistingFile(): void
    {
        // Arrange
        file_put_contents($this->target, 'SENTINEL');

        // Act
        [$exit] = $this->runCommand(['--force' => true]);

        // Assert — file replaced with the generated stub
        $this->assertSame(0, $exit);
        $content = (string) file_get_contents($this->target);
        $this->assertStringNotContainsString('SENTINEL', $content);
        $this->assertStringContainsString('WebhookHandler', $content);
    }

    // =========================================================================
    // .env.example handling
    // =========================================================================

    /**
     * When .env.example exists without a WEBHOOK_SECRET key, the command must
     * append the key (with explanatory comment) and report it.
     */
    public function testAppendsWebhookSecretToEnvExample(): void
    {
        // Arrange — .env.example without the key
        file_put_contents($this->envExample, "APP_DEBUG=0\n");

        // Act
        [$exit, $out] = $this->runCommand();

        // Assert
        $this->assertSame(0, $exit);
        $this->assertStringContainsString('Appended WEBHOOK_SECRET= to .env.example', $out);
        $env = (string) file_get_contents($this->envExample);
        $this->assertStringContainsString('WEBHOOK_SECRET=', $env);
        $this->assertStringContainsString('APP_DEBUG=0', $env,
            'Existing .env.example content must be preserved');
    }

    /**
     * When .env.example already contains WEBHOOK_SECRET, the command must not
     * append a duplicate entry.
     */
    public function testDoesNotDuplicateWebhookSecretInEnvExample(): void
    {
        // Arrange — key already present
        file_put_contents($this->envExample, "WEBHOOK_SECRET=existing\n");

        // Act
        [$exit, $out] = $this->runCommand();

        // Assert — no "Appended" message and only one occurrence of the key
        $this->assertSame(0, $exit);
        $this->assertStringNotContainsString('Appended WEBHOOK_SECRET', $out);
        $env = (string) file_get_contents($this->envExample);
        $this->assertSame(1, substr_count($env, 'WEBHOOK_SECRET'),
            'WEBHOOK_SECRET must not be appended twice');
    }

    /**
     * Next-step instructions must always be printed on success so the user
     * knows how to wire the webhook up in GitHub/Bitbucket.
     */
    public function testPrintsNextSteps(): void
    {
        // Arrange / Act
        [, $out] = $this->runCommand();

        // Assert
        $this->assertStringContainsString('Next steps:', $out);
        $this->assertStringContainsString('webhook.php', $out);
    }

    // =========================================================================
    // detectCliName() — private helper coverage
    // =========================================================================

    /**
     * detectCliName() must return the lowercase namespace when app/app.php
     * exists and returns an array with a 'namespace' key that has a matching
     * entry-point .php file in root.
     *
     * Covers the "namespace found + matching root PHP file exists" branch
     * inside detectCliName() (lines 97–100 of MakeWebhook).
     */
    public function testDetectCliNameUsesNamespaceWhenAppPhpExistsAndEntryFilePresent(): void
    {
        // Arrange — build a synthetic root that has:
        //   app/app.php  → returns ['namespace' => 'MyApp']
        //   myapp.php    → the entry-point file
        $root = sys_get_temp_dir() . '/mkwh_test_' . bin2hex(random_bytes(4));
        mkdir($root . '/app', 0777, true);
        file_put_contents($root . '/app/app.php', '<?php return ["namespace" => "MyApp"];');
        file_put_contents($root . '/myapp.php', '<?php // entry point');

        try {
            // Act — call via reflection
            $command  = new MakeWebhook();
            $ref      = new \ReflectionMethod($command, 'detectCliName');
            $cliName  = $ref->invoke($command, $root);

            // Assert — namespace 'MyApp' lowercased → 'myapp', matching myapp.php
            $this->assertSame('myapp', $cliName,
                'detectCliName() must return the lowercased namespace when a matching entry file exists');
        } finally {
            @unlink($root . '/app/app.php');
            @unlink($root . '/myapp.php');
            @rmdir($root . '/app');
            @rmdir($root);
        }
    }

    /**
     * detectCliName() must return the namespace (without an entry-point file)
     * when app/app.php has a namespace key but no matching .php file in root.
     *
     * Covers the branch at line 102: `return $candidate ?: 'pramnos'`.
     */
    public function testDetectCliNameReturnsNamespaceWhenEntryFileAbsent(): void
    {
        // Arrange — app.php exists with namespace, but no matching root .php file
        $root = sys_get_temp_dir() . '/mkwh_test_' . bin2hex(random_bytes(4));
        mkdir($root . '/app', 0777, true);
        file_put_contents($root . '/app/app.php', '<?php return ["namespace" => "Acme"];');
        // No acme.php in root

        try {
            // Act
            $command  = new MakeWebhook();
            $ref      = new \ReflectionMethod($command, 'detectCliName');
            $cliName  = $ref->invoke($command, $root);

            // Assert — namespace used even though file doesn't exist
            $this->assertSame('acme', $cliName,
                'detectCliName() must return the lowercased namespace even when no entry file exists');
        } finally {
            @unlink($root . '/app/app.php');
            @rmdir($root . '/app');
            @rmdir($root);
        }
    }

    /**
     * detectCliName() falls through to scanning the root when app/app.php is absent,
     * and identifies the entry point by what it contains rather than by its position.
     */
    public function testDetectCliNameUsesGlobWhenNoAppPhpExists(): void
    {
        // Arrange — a root with a real console entry point and no app/app.php, plus a
        // stray script that sorts before it. Until 2026-08-16 the stray won: the scan
        // took the first *.php that was not one of three excluded names, so any file
        // left in the root became the CLI name. This test asserted that as the
        // contract, with `<?php // entry point` as its whole fixture — a file that
        // proves nothing about being an entry point.
        $root = sys_get_temp_dir() . '/mkwh_test_' . bin2hex(random_bytes(4));
        mkdir($root, 0777, true);
        file_put_contents($root . '/aaa-scratch.php', '<?php // left here by somebody');
        file_put_contents(
            $root . '/mywebapp.php',
            "<?php\n\$consoleApp = new \\MyWebApp\\Console('MyWebApp CLI');\n\$consoleApp->run();\n"
        );

        try {
            // Act
            $command = new MakeWebhook();
            $ref     = new \ReflectionMethod($command, 'detectCliName');
            $cliName = $ref->invoke($command, $root);

            // Assert — the entry point is identified by what it does, not by position
            $this->assertSame('mywebapp', $cliName,
                'detectCliName() must find the console entry point, not the first file in the directory');
        } finally {
            @unlink($root . '/mywebapp.php');
            @unlink($root . '/aaa-scratch.php');
            @rmdir($root);
        }
    }
}
