<?php

declare(strict_types=1);

namespace Pramnos\Tests\Characterization\Auth;

use PHPUnit\Framework\TestCase;
use Pramnos\Application\Application;
use Pramnos\Application\Settings;
use Pramnos\Auth\Permissions;
use Pramnos\Framework\Factory;
use Pramnos\User\User;

/**
 * Abstract base for Permissions characterization tests.
 *
 * Subclasses connect to a specific database (MySQL or PostgreSQL) and run
 * the same behavioral contracts. The goal is to lock the observable behavior
 * of Permissions::allow(), deny(), removePermission(), and isAllowed() before
 * any internal migration to QueryBuilder touches the class.
 *
 * Why this matters: Permissions uses raw SQL with backtick-quoted identifiers.
 * Database::query() already translates backticks to double-quotes on PostgreSQL,
 * so the class is expected to work correctly on all three backends. These tests
 * verify that assumption and provide a safety net for the QB migration.
 */
abstract class PermissionsCharacterizationBase extends TestCase
{
    protected \Pramnos\Database\Database $db;

    /** Unique random resource name to avoid cross-test collisions. */
    protected string $resource = '';

    /** Actual table name (DB_PERMISSIONSTABLE with prefix substituted). */
    protected string $permTable = '';

    // ── Subclass contract ─────────────────────────────────────────────────────

    /**
     * Load the correct settings file and connect to the target database.
     * Must populate $this->db.
     */
    abstract protected function connectDatabase(): void;

    // ── PHPUnit lifecycle ─────────────────────────────────────────────────────

    protected function setUp(): void
    {
        // Arrange — connect to the right DB and bootstrap constants
        $this->connectDatabase();

        // Build the real table name for direct cleanup queries
        $this->permTable = str_replace(
            '#PREFIX#',
            $this->db->prefix,
            DB_PERMISSIONSTABLE
        );

        // Create the permissions table (no FK — users table may not exist)
        Permissions::setupDb(false);
        User::setupDb();

        // Use a per-test unique resource string to prevent cross-test leakage
        $this->resource = 'char_perm_res_' . bin2hex(random_bytes(4));
    }

    protected function tearDown(): void
    {
        // Remove only rows generated by this test run
        $this->db->queryBuilder()
            ->table($this->permTable)
            ->where('resource', $this->resource)
            ->delete();
        $this->db->cacheflush('permissions');
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    /**
     * Returns a fresh Permissions instance (bypasses the singleton so each
     * test starts with a clean in-memory cache).
     */
    private function makePerm(): Permissions
    {
        return new Permissions('database');
    }

    // ── Tests — allow / deny / remove cycle ──────────────────────────────────

    /**
     * Verifies that allow() persists a value=1 record and isAllowed() reads
     * it back from the database (group subject type, no users table needed).
     *
     * This is the most fundamental contract: granting access must be readable.
     */
    public function testAllowMakesGroupPrivilegeAllowed(): void
    {
        // Arrange
        $perm = $this->makePerm();

        // Act
        $perm->allow('editors', $this->resource, 'edit', '', 'module', 'group');

        // Assert — fresh instance bypasses the in-memory cache
        $result = $this->makePerm()->isAllowed(
            'editors', $this->resource, 'edit', '', 'module', 'group'
        );
        $this->assertTrue($result, 'allow() must store value=1 so isAllowed() returns true');
    }

    /**
     * Verifies that deny() persists a value=0 record and isAllowed() returns
     * false — an explicit deny overrides any default.
     */
    public function testDenyMakesGroupPrivilegeDenied(): void
    {
        // Arrange
        $perm = $this->makePerm();

        // Act
        $perm->deny('guests', $this->resource, 'delete', '', 'module', 'group');

        // Assert
        $result = $this->makePerm()->isAllowed(
            'guests', $this->resource, 'delete', '', 'module', 'group'
        );
        $this->assertFalse($result, 'deny() must store value=0 so isAllowed() returns false');
    }

    /**
     * Verifies that removePermission() physically deletes the record so that
     * isAllowed() no longer finds an explicit entry and falls back to the
     * default (false when none is set, with nonExistEqualsFalse=true).
     */
    public function testRemovePermissionDeletesRecordForGroup(): void
    {
        // Arrange
        $perm = $this->makePerm();
        $perm->allow('viewers', $this->resource, 'read', '', 'module', 'group');

        // Verify the record exists before removal
        $this->assertTrue(
            $this->makePerm()->isAllowed(
                'viewers', $this->resource, 'read', '', 'module', 'group'
            ),
            'Pre-condition: permission must exist'
        );

        // Act
        $perm->removePermission(
            'viewers', $this->resource, 'read', '', 'module', 'group'
        );

        // Assert — no record + no default → false
        $result = $this->makePerm()->isAllowed(
            'viewers', $this->resource, 'read', '', 'module', 'group'
        );
        $this->assertFalse(
            $result,
            'After removePermission(), isAllowed() must return false (no default set)'
        );
    }

    /**
     * Verifies that calling allow() after deny() updates the existing record
     * so isAllowed() returns the new value (true), not the old one.
     *
     * setPermission() DELETEs then INSERTs — this test documents that a
     * permission update is effectively an upsert.
     */
    public function testAllowOverwritesPreviousDeny(): void
    {
        // Arrange
        $perm = $this->makePerm();
        $perm->deny('admins', $this->resource, 'publish', '', 'module', 'group');

        // Act
        $perm->allow('admins', $this->resource, 'publish', '', 'module', 'group');

        // Assert
        $result = $this->makePerm()->isAllowed(
            'admins', $this->resource, 'publish', '', 'module', 'group'
        );
        $this->assertTrue($result, 'allow() after deny() must update the stored value to 1');
    }

    // ── Tests — user type permissions ─────────────────────────────────────────

    /**
     * Verifies user-type permissions using nonExistEqualsFalse=false to avoid
     * the group-membership lookup (which requires the users table).
     *
     * With nonExistEqualsFalse=false:
     *   - Permission found  → returns bool (true or false from DB)
     *   - Permission absent → returns NULL (no fallback lookup)
     */
    public function testAllowAndIsAllowedForUserType(): void
    {
        // Arrange — use a numeric user ID unlikely to conflict
        $userId = 9001;
        $perm   = $this->makePerm();

        // Act
        $perm->allow($userId, $this->resource, 'view');

        // Assert — read back with nonExistEqualsFalse=false to skip group lookup
        $result = $this->makePerm()->isAllowed(
            $userId, $this->resource, 'view', '', 'module', 'user', false
        );
        $this->assertTrue(
            (bool)$result,
            'User-type allow() must persist value=1 readable by isAllowed()'
        );
    }

    /**
     * Verifies deny for user-type stores value=0 and isAllowed() returns false.
     */
    public function testDenyAndIsAllowedForUserType(): void
    {
        // Arrange
        $userId = 9002;
        $perm   = $this->makePerm();

        // Act
        $perm->deny($userId, $this->resource, 'delete');

        // Assert
        $result = $this->makePerm()->isAllowed(
            $userId, $this->resource, 'delete', '', 'module', 'user', false
        );
        $this->assertFalse(
            (bool)$result,
            'User-type deny() must persist value=0 readable by isAllowed()'
        );
    }

    // ── Tests — nonExistEqualsFalse ───────────────────────────────────────────

    /**
     * Verifies that isAllowed() returns NULL (not false) when nonExistEqualsFalse
     * is false and no permission record exists.
     *
     * The distinction matters because NULL means "not specified" while false means
     * "explicitly denied". Callers can use this to implement fallback hierarchies.
     */
    public function testIsAllowedReturnsNullForMissingPermissionWhenFlagIsFalse(): void
    {
        // Arrange — no records inserted
        $perm = $this->makePerm();

        // Act
        $result = $perm->isAllowed(
            'nobody', $this->resource, 'fly', '', 'module', 'group', false
        );

        // Assert
        $this->assertNull(
            $result,
            'With nonExistEqualsFalse=false and no record, isAllowed() must return NULL'
        );
    }

    // ── Tests — setDefaultPermission ─────────────────────────────────────────

    /**
     * Verifies that setDefaultPermission() causes isAllowed() to return the
     * default when no explicit record exists for that privilege.
     *
     * The default is stored in-memory on the Permissions instance, so it only
     * applies to calls on the same instance — this is expected behavior.
     */
    public function testDefaultPermissionIsReturnedWhenNoRecordExists(): void
    {
        // Arrange
        $perm = $this->makePerm();
        $perm->setDefaultPermission('read', true);

        // Act — no record for this privilege was inserted
        $result = $perm->isAllowed(
            'anonymous', $this->resource, 'read', '', 'module', 'group'
        );

        // Assert
        $this->assertTrue(
            $result,
            'setDefaultPermission(read, true) must be returned when no DB record exists'
        );
    }

    /**
     * Verifies that an explicit DB record overrides the default permission.
     * deny() sets value=0 — even when the default is true, the DB record wins.
     */
    public function testExplicitDenyOverridesDefaultAllow(): void
    {
        // Arrange
        $perm = $this->makePerm();
        $perm->setDefaultPermission('read', true);
        $perm->deny('blocked', $this->resource, 'read', '', 'module', 'group');

        // Act
        $result = $this->makePerm()->isAllowed(
            'blocked', $this->resource, 'read', '', 'module', 'group'
        );

        // Assert — explicit DB deny must win over the default
        $this->assertFalse(
            $result,
            'An explicit deny record must override the default true permission'
        );
    }

    // ── Tests — instance cache ────────────────────────────────────────────────

    /**
     * Verifies that the in-memory cache on a Permissions instance is populated
     * on the first isAllowed() call so that subsequent calls return the same
     * result without hitting the database again.
     *
     * This is observable because allow() clears cacheflush('permissions') on
     * the DB but NOT the instance-level _cache. A second isAllowed() on the
     * same object after a mutation by a different instance should still return
     * the cached value.
     */
    public function testInstanceCacheServesSubsequentCalls(): void
    {
        // Arrange
        $perm1 = $this->makePerm();
        $perm1->allow('role_a', $this->resource, 'export', '', 'module', 'group');

        $perm2 = $this->makePerm();

        // Act — first call populates cache
        $first = $perm2->isAllowed(
            'role_a', $this->resource, 'export', '', 'module', 'group'
        );

        // Mutate via a different instance (perm3) — changes DB but not perm2's cache
        $perm3 = $this->makePerm();
        $perm3->deny('role_a', $this->resource, 'export', '', 'module', 'group');

        // Second call on perm2 must still return the cached (old) value
        $second = $perm2->isAllowed(
            'role_a', $this->resource, 'export', '', 'module', 'group'
        );

        // Assert
        $this->assertTrue($first, 'First isAllowed() must return true');
        $this->assertTrue(
            $second,
            'Second isAllowed() on same instance must return the cached value (true), not the mutated DB value'
        );
    }

    // ── Tests — admin escalation ──────────────────────────────────────────────

    /**
     * Verifies that granting the "admin" privilege on a resource causes
     * isAllowed() to return true for any other privilege on that same resource
     * without an explicit allow record.
     *
     * This is the admin escalation shortcut in _isAllowed():
     *   if resourceType=='module' && privilege!='admin' => check admin first
     */
    public function testAdminPrivilegeGrantsAllPrivilegesOnResource(): void
    {
        // Arrange — grant only 'admin' on the resource
        $perm = $this->makePerm();
        $perm->allow('superuser', $this->resource, 'admin', '', 'module', 'group');

        // Act — check a privilege that was never explicitly set
        $result = $this->makePerm()->isAllowed(
            'superuser', $this->resource, 'delete', '', 'module', 'group'
        );

        // Assert
        $this->assertTrue(
            $result,
            'A group with admin privilege on a resource must be allowed any other privilege on it'
        );
    }

    /**
     * Verifies that admin escalation does NOT apply when checking the admin
     * privilege itself — it goes directly to the DB lookup to avoid infinite
     * recursion.
     */
    public function testAdminPrivilegeCheckDoesNotRecurseInfinitely(): void
    {
        // Arrange — no permissions set
        $perm = $this->makePerm();

        // Act — check 'admin' on a resource that has no record
        $result = $perm->isAllowed(
            'nobody', $this->resource, 'admin', '', 'module', 'group'
        );

        // Assert — should return false without recursion or error
        $this->assertFalse(
            $result,
            'isAllowed() for admin on a resource with no record must return false'
        );
    }

    // ── Tests — setupDb ───────────────────────────────────────────────────────

    /**
     * Verifies that setupDb() is idempotent — calling it twice does not throw
     * an error and the table remains usable.
     */
    public function testSetupDbIsIdempotent(): void
    {
        // Act — call twice (first was in setUp())
        Permissions::setupDb(false);

        // Assert — table must still accept writes
        $perm = $this->makePerm();
        $perm->allow('idempotent_role', $this->resource, 'read', '', 'module', 'group');

        $result = $this->makePerm()->isAllowed(
            'idempotent_role', $this->resource, 'read', '', 'module', 'group'
        );
        $this->assertTrue($result, 'Table must still be functional after double setupDb()');
    }
}
