<?php

namespace Pramnos\Tests;
use Pramnos\Translator\Language;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-16 at 23:47:16.



 */
#[\PHPUnit\Framework\Attributes\CoversClass(\Pramnos\Translator\Language::class)]
class LanguageTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Language
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Language();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    
    public function testGetlang()
    {
        $this->assertTrue(is_array($this->object->getLang()));
    }

    
    public function testAddlang()
    {
        $this->object->addlang(array('test' => 'test'));
        $lang = $this->object->getlang();
        $this->assertTrue(is_array($lang));
        $this->assertTrue(isset($lang['test']));
        $this->assertEquals($lang['test'], 'test');
    }

    
    public function test_()
    {
        $lang = array(
            'Translated String' => 'a translated string'
        );
        $this->assertEquals('test string', $this->object->_('test string'));
        $this->object->addlang($lang);
        $this->assertEquals('a translated string',
                            $this->object->_('Translated String'));
    }

    
    public function testCurrentlang()
    {
        $this->object->setLang('greek');
        $this->assertEquals($this->object->currentlang(), 'greek');
    }

    
    public function testSetLang()
    {
        $this->assertTrue(
            $this->object->setLang(
                'greek'
            ) instanceof \Pramnos\Translator\Language
        );
    }

    
    public function testSetLangWithNonString()
    {
        $this->expectException('Exception');
        $this->object->setLang(array());
    }

    
    public function testGetInstance()
    {
        $this->assertTrue(
            Language::getInstance() instanceof \Pramnos\Translator\Language
        );
    }

}
