<?php

use Pramnos\Http\Request;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2014-10-26 at 17:28:07.



 * 
 */
#[\PHPUnit\Framework\Attributes\RunTestsInSeparateProcesses]
#[\PHPUnit\Framework\Attributes\CoversClass(\Pramnos\Http\Request::class)]
#[\PHPUnit\Framework\Attributes\IgnoreDeprecations]
class RequestTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Request
     */
    protected $_object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        if (!isset($_SERVER['HTTP_HOST'])) {
            $_SERVER['HTTP_HOST'] = 'localhost';
            $_SERVER['SERVER_PORT'] = 80;
            $_SERVER['SERVER_NAME'] = 'localhost';
            $_SERVER['REMOTE_ADDR'] = '127.0.0.1';
            $_SERVER['HTTP_USER_AGENT'] = 'PHPUnit Tests';
            $_SERVER['REQUEST_URI'] = '/pramnosframework/';
        }
        $_GET['r'] = 'controller/display/option';
        $this->_object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    
    /**
     * Test singleton instance retrieval
     */
    public function testGetInstance()
    {
        $_GET['r'] = 'controller/action.html/option';
        $_SERVER['REQUEST_URI'] = 'controller/action.html/option?test=test';
        $this->assertInstanceOf(
            'Pramnos\Http\Request', Request::getInstance()
        );
    }

    
    /**
     * Test static factory create method
     */
    public function testCreate()
    {
        $this->assertInstanceOf(
            'Pramnos\Http\Request', Request::create("/", "GET")
        );
    }

    
    /**
     * Test retrieval of the URL option segment
     */
    public function testGetOption()
    {
        unset($_GET['_option']);
        $this->assertEquals(NULL, $this->_object->getOption());
        $_GET['_option'] = 'test';
        $this->assertEquals('test', $this->_object->getOption());
    }

    
    /**
     * Test static retrieval of the URL option segment
     */
    public function testStaticGetOption()
    {
        if (isset($_GET['_option'])) {
            unset($_GET['_option']);
        }
        $this->assertEquals(NULL, Request::staticGetOption());
        $_GET['_option'] = 'test';
        $this->assertEquals('test', Request::staticGetOption());
    }

    
    /**
     * Test basic data retrieval from various sources
     */
    public function testGet()
    {
        $_GET['test'] = 'test';
        $_POST['test2'] = 'test2';
        $this->assertEquals('test', $this->_object->get('test', '', 'get'));
        $this->assertEquals('test2', $this->_object->get('test2', '', 'post'));
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'post')
        );
    }

    
    /**
     * Test static data retrieval from various sources
     */
    public function testStaticGet()
    {
        $this->assertEquals(
            'test', Request::staticGet('test', 'test', 'get')
        );
        $this->assertEquals(
            'test', Request::staticGet('test', 'test', 'post')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'REQUEST')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'FILES')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'COOKIE')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'ENV')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'SESSION')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'default')
        );
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'SERVER')
        );
        $_POST['test3'] = 'test3';
        $this->assertEquals(
            'test3', $this->_object->get('test3', 'test3', 'post')
        );
        $this->assertEquals(
            0, $this->_object->get('test3', 'test3', 'post', 'int')
        );
        $this->assertIsInt($this->_object->get('test3', 'test3', 'post', 'int'));
    }

    
    /**
     * Test module (controller) getter and setter
     */
    public function testGetAndSetModule()
    {
        $this->_object->setModule('test');
        $this->assertEquals('test', $this->_object->getModule());
        $this->_object->setModule('');
    }

    
    /**
     * Test action getter and setter
     */
    public function testSetAndGetAction()
    {
        $this->assertEquals('display', $this->_object->getAction());
        $this->_object->setAction('');
        $this->assertEquals('', $this->_object->getAction());
    }



    
    /**
     * Test URL generation
     */
    public function testGetURL()
    {
        $this->assertIsString($this->_object->getURL());
        $this->assertIsString($this->_object->getURL(false));
        $_SERVER["HTTPS"] = 'on';
        $this->assertIsString($this->_object->getURL(false));
        $_SERVER["SERVER_PORT"] = '123123';
        $this->assertIsString($this->_object->getURL(false));
    }

    /**
     * Test HTTPS protocol detection
     */
    public function testIsHttps()
    {
        $_SERVER["HTTPS"] = 'on';
        $this->assertTrue($this->_object->isHttps());
        
        $_SERVER["HTTPS"] = 'off';
        $this->assertFalse($this->_object->isHttps());

        unset($_SERVER["HTTPS"]);
        $this->assertFalse($this->_object->isHttps());
    }

    /**
     * Test cookie setting logic
     */
    public function testCookieset()
    {
        // Headers are likely sent during testing, but we check if the method executes
        // without crashing and follows the logic.
        $result = $this->_object->cookieset('testcookie', 'testvalue', time() + 3600);
        
        // Since setcookie fails in CLI if headers are 'sent' or if we're not output-buffered,
        // we can't reliably assert TRUE here, but we can verify it doesn't fail syntactically.
        $this->assertIsBool($result);
    }

    /**
     * Test basic cookie retrieval logic
     */
    public function testCookieget()
    {
        $cookiename = 'testcookie';
        $value = 'testvalue';
        
        $realCookiename = str_rot13($cookiename);
        $prefix = substr(md5('pcms'), 0, 10);
        
        $_COOKIE[$prefix][$realCookiename] = $value;
        
        $this->assertEquals($value, $this->_object->cookieget($cookiename));
        $this->assertNull($this->_object->cookieget('nonexistent'));
    }

    /**
     * Test URL parameter calculation with various segments
     */
    public function testCalcParams()
    {
        // Test with query string simulation
        $_SERVER['REQUEST_URI'] = '/controller/action/param/value?extra=1';
        $this->_object->calcParams('controller/action/param/value');
        
        $this->assertEquals('controller', $this->_object->getController());
        $this->assertEquals('action', $this->_object->getAction());
        $this->assertEquals('value', $_GET['param']);
        $this->assertEquals('1', $_GET['extra']);

        // Test with _option fallback
        $this->_object->calcParams('controller/action/single-option');
        $this->assertEquals('single-option', $_GET['_option']);
    }

    /**
     * Test PUT and DELETE method data handling
     */
    public function testPutAndDeleteHandling()
    {
        // Test PUT with JSON
        Request::setRawInput(json_encode(['foo' => 'bar']));
        $_SERVER['REQUEST_METHOD'] = 'PUT';
        $request = new Request();
        
        $this->assertEquals('bar', $request->get('foo', null, 'put'));
        
        // Test DELETE
        Request::setRawInput('id=123');
        $_SERVER['REQUEST_METHOD'] = 'DELETE';
        $request = new Request();
        
        $this->assertEquals('123', $request->get('id', null, 'delete'));
    }

    /**
     * Test JSON expansion from GET keys
     */
    public function testJsonInGetKeys()
    {
        // Feature: JSON encoded in GET keys is expanded
        $jsonKey = str_replace(' ', '_', json_encode(['data' => 'expanded']));
        $_GET[$jsonKey] = '1';
        $_SERVER['REQUEST_METHOD'] = 'GET';
        
        $request = new Request();
        $this->assertEquals('expanded', $request->get('data', null, 'get'));
    }

    /**
     * Test all() and only() data helper methods
     */
    public function testAllAndOnlyMethods()
    {
        $_POST = ['a' => 1, 'b' => 2];
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $request = new Request();
        
        $this->assertEquals($_POST, $request->all());
        $this->assertEquals($_POST, $request->all('post'));
        $this->assertEquals(['a' => 1], $request->only(['a']));
        
        $_GET = ['x' => 10];
        $this->assertEquals($_GET, $request->all('get'));
    }

    /**
     * Test getArray() conversion to objects
     */
    public function testGetArray()
    {
        $_GET['data'] = ['key' => 'val'];
        $result = $this->_object->getArray('data', null, 'get');
        
        $this->assertIsObject($result);
        $this->assertEquals('val', $result->key);
        
        $this->assertEquals('fallback', $this->_object->getArray('none', 'fallback'));
    }

    /**
     * Test loading and clearing flashed validation state
     */
    public function testValidationStateHandling()
    {
        // Reset static properties to force loading from session
        $reflection = new \ReflectionClass(Request::class);
        $errorsProp = $reflection->getProperty('validationErrors');
        $errorsProp->setAccessible(true);
        $errorsProp->setValue(null, null);
        
        $oldProp = $reflection->getProperty('oldInput');
        $oldProp->setAccessible(true);
        $oldProp->setValue(null, null);

        $_SESSION['_validation_errors'] = ['field' => ['error']];
        $_SESSION['_old_input'] = ['name' => 'John'];
        
        // Constructor loads state
        $request = new Request();
        
        $this->assertEquals(['field' => ['error']], $request->errors());
        $this->assertEquals('John', $request->old('name'));
        $this->assertEquals(['name' => 'John'], $request->old());
        
        $request->clearValidationState();
        $this->assertEmpty($request->errors());
        $this->assertEmpty($request->old());
        $this->assertArrayNotHasKey('_validation_errors', $_SESSION);
    }

    /**
     * Test absolute URL generation with different ports
     */
    public function testGetURLWithDifferentPorts()
    {
        $_SERVER['REQUEST_URI'] = '/test';
        $_SERVER['SERVER_NAME'] = 'example.com';
        
        $_SERVER['SERVER_PORT'] = '8080';
        unset($_SERVER['HTTPS']);
        $this->assertEquals('http://example.com:8080/test', $this->_object->getURL(false));
        
        $_SERVER['SERVER_PORT'] = '80';
        $this->assertEquals('http://example.com/test', $this->_object->getURL(false));
    }

    /**
     * Test the validate() helper method
     */
    public function testValidateHelper()
    {
        $_POST = ['name' => 'John'];
        $_SERVER['REQUEST_METHOD'] = 'POST';
        $request = new Request();
        
        $validated = $request->validate(['name' => 'required'], [], [], 'post');
        $this->assertEquals(['name' => 'John'], $validated);
    }

    /**
     * Test URL parsing with odd number of segments
     */
    public function testCalcParamsWithOddParts()
    {
        // controller/action/param (odd number of parts after controller/action)
        $_GET = [];
        unset($_GET['_option']);
        $this->_object->calcParams('controller/action/param');
        
        $this->assertArrayNotHasKey('param', $_GET);
        $this->assertEquals('param', $_GET['_option']);
    }

    /**
     * Test POST requests with JSON payloads
     */
    public function testPostWithJson()
    {
        $_POST = [];
        $_SERVER['REQUEST_METHOD'] = 'POST';
        Request::setRawInput(json_encode(['post_json' => 'ok']));
        
        $request = new Request();
        $this->assertEquals('ok', $_POST['post_json']);
    }

    /**
     * Test PUT requests with form-encoded data
     */
    public function testPutWithNonJson()
    {
        $_SERVER['REQUEST_METHOD'] = 'PUT';
        Request::setRawInput('a=1&b=2');
        
        $request = new Request();
        $this->assertEquals('1', $request->get('a', null, 'put'));
    }

    /**
     * Test default cookie expiration time calculation
     */
    public function testCookiesetDefaultTime()
    {
        // Passing 0 as time should trigger default time calculation
        $result = $this->_object->cookieset('default_time_cookie', 'val', 0);
        $this->assertIsBool($result);
    }

    /**
     * Test staticGet fallback behavior
     */
    public function testStaticGetDefaultCase()
    {
        $_REQUEST['def'] = 'val';
        $this->assertEquals('val', Request::staticGet('def', null, 'UNKNOWN_METHOD'));
    }

    /**
     * Test retrieving all data from various sources
     */
    public function testAllSourcesDetailed()
    {
        if (!isset($_SESSION)) {
            $_SESSION = [];
        }
        if (!isset($_ENV)) {
            $_ENV = [];
        }
        $sources = ['FILES', 'COOKIE', 'ENV', 'SESSION', 'SERVER'];
        foreach ($sources as $source) {
            $this->assertIsArray($this->_object->all($source));
        }
    }
}
