<?php

namespace Pramnos\Framework;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-19 at 15:27:11.
 */
class BaseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Base
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Base;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Pramnos\Framework\Base::_setParentObject
     * @todo   Implement test_setParentObject().
     */
    public function test_setParentObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_getParentObject
     * @todo   Implement test_getParentObject().
     */
    public function test_getParentObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::__set
     * @todo   Implement test__set().
     */
    public function test__set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::__get
     * @todo   Implement test__get().
     */
    public function test__get()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::addError
     * @todo   Implement testAddError().
     */
    public function testAddError()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::addMessage
     * @todo   Implement testAddMessage().
     */
    public function testAddMessage()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_getErrors
     * @todo   Implement test_getErrors().
     */
    public function test_getErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_getMessages
     * @todo   Implement test_getMessages().
     */
    public function test_getMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_printMessages
     * @todo   Implement test_printMessages().
     */
    public function test_printMessages()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_printErrors
     * @todo   Implement test_printErrors().
     */
    public function test_printErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::hasErrors
     * @todo   Implement testHasErrors().
     */
    public function testHasErrors()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Base::_set
     * @todo   Implement test_set().
     */
    public function test_set()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
