<?php
namespace Pramnos\Framework;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-21 at 07:17:13.
 */
class ContainerTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Container
     */
    protected $container;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->container = new Container;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        $this->container = null;
    }

    /**
     * @covers Pramnos\Framework\Container
     */
    public function testRegister()
    {
        $this->assertInstanceOf(
            "\Pramnos\Framework\Container",
            $this->container->register(
                'request',
                function($c) {
                    return new \Pramnos\Http\Request();
                }
            )
        );
        $this->assertInstanceOf(
            "\Pramnos\Framework\Container",
            $this->container->register(
                'request',
                function($c) {
                    return null;
                }
            )
        );

        $this->assertInstanceOf(
            "\Pramnos\Http\Request",
            $this->container->get('request')
        );

    }

    /**
     * @covers Pramnos\Framework\Container::deRegister
     * @todo   Implement testDeRegister().
     */
    public function testDeRegister()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Container::sigleton
     * @todo   Implement testSigleton().
     */
    public function testSigleton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Pramnos\Framework\Container::get
     * @todo   Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
