<?php

namespace Pramnos\Framework;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-19 at 15:27:11.
 */
class BaseTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var Base
     */
    protected $object;

    protected function setUp(): void
    {
        $this->object = new Base;
    }

    protected function tearDown(): void
    {
    }

    public function testBaseInstantiation()
    {
        $this->assertInstanceOf('\Pramnos\Framework\Base', $this->object);
    }
}
