<?php

namespace Pramnos\Tests;
use Pramnos\Translator\Language;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-05-16 at 23:47:16.



 */
#[\PHPUnit\Framework\Attributes\CoversClass(\Pramnos\Translator\Language::class)]
class LanguageTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var Language
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Language();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(): void
    {

    }

    
    public function testGetlang()
    {
        $this->assertTrue(is_array($this->object->getLang()));
    }

    
    public function testAddlang()
    {
        $this->object->addlang(array('test' => 'test'));
        $lang = $this->object->getlang();
        $this->assertTrue(is_array($lang));
        $this->assertTrue(isset($lang['test']));
        $this->assertEquals($lang['test'], 'test');
    }

    
    public function test_()
    {
        $lang = array(
            'Translated String' => 'a translated string'
        );
        $this->assertEquals('test string', $this->object->_('test string'));
        $this->object->addlang($lang);
        $this->assertEquals('a translated string',
                            $this->object->_('Translated String'));
    }

    
    public function testCurrentlang()
    {
        $this->object->setLang('greek');
        $this->assertEquals($this->object->currentlang(), 'greek');
    }

    
    public function testSetLang()
    {
        $this->assertTrue(
            $this->object->setLang(
                'greek'
            ) instanceof \Pramnos\Translator\Language
        );
    }

    
    public function testSetLangWithNonString()
    {
        $this->expectException('Exception');
        $this->object->setLang(array());
    }


    public function testGetInstance()
    {
        $this->assertTrue(
            Language::getInstance() instanceof \Pramnos\Translator\Language
        );
    }

    /**
     * Language::load() must return false when neither the custom path nor the
     * ROOT language directory contains a matching file.
     *
     * This covers the final `return false` branch in load() (line ~151) reached
     * when a non-existent path is given and no fallback files are found.
     */
    public function testLoadReturnsFalseWhenNoFileFound(): void
    {
        // Arrange — a path with no language files
        $nonExistentPath = sys_get_temp_dir() . '/pramnos_lang_test_' . bin2hex(random_bytes(4));
        @mkdir($nonExistentPath . '/language', 0777, true);

        // Act
        $result = $this->object->load('nonexistentlang', $nonExistentPath);

        // Assert — no file found, must return false
        $this->assertFalse($result, 'load() must return false when no language file exists');

        // Cleanup
        @rmdir($nonExistentPath . '/language');
        @rmdir($nonExistentPath);
    }

    /**
     * Language::load() with a custom path must load strings from
     * <path>/language/<lang>.php when that file exists.
     *
     * This covers the `if (file_exists(...))` true branch in the else-block
     * (lines ~131-133 of load()), which is only reached when $path != ''.
     */
    public function testLoadWithCustomPathLoadsStrings(): void
    {
        // Arrange — write a minimal language file to a temp directory
        $tmpDir  = sys_get_temp_dir() . '/pramnos_lang_test_' . bin2hex(random_bytes(4));
        $langDir = $tmpDir . '/language';
        @mkdir($langDir, 0777, true);
        file_put_contents(
            $langDir . '/testlang.php',
            "<?php\n\$lang = ['greeting' => 'Hello from testlang'];\n"
        );

        // Act
        $result = $this->object->load('testlang', $tmpDir);

        // Assert — file was loaded, key is accessible
        $this->assertTrue($result, 'load() must return true when language file exists');
        $strings = $this->object->getlang();
        $this->assertArrayHasKey('greeting', $strings, 'load() must merge strings from custom path');
        $this->assertSame('Hello from testlang', $strings['greeting']);

        // Cleanup
        @unlink($langDir . '/testlang.php');
        @rmdir($langDir);
        @rmdir($tmpDir);
    }

    /**
     * Language::getFlag() must return false when no flag PNG exists for the
     * current language.
     *
     * This covers the else branch (return false) of getFlag() at line ~221,
     * reached when no <lang>.png exists in the language directory.
     */
    public function testGetFlagReturnsFalseWhenNoImageExists(): void
    {
        // Act — no language flag image expected in the test environment
        $result = $this->object->getFlag('nonexistent_language_xyzzy');

        // Assert
        $this->assertFalse($result, 'getFlag() must return false when the PNG file does not exist');
    }

    /**
     * Language::getFlag() with an empty argument uses the current language.
     *
     * This covers the `if ($lang == '')` branch at the top of getFlag() that
     * sets $lang = $this->_lang when no argument is given.
     */
    public function testGetFlagWithNoArgUsesCurrentLanguage(): void
    {
        // Arrange — set to a language that certainly has no PNG
        $this->object->setLang('nonexistent_xyzzy');

        // Act — call with no argument
        $result = $this->object->getFlag();

        // Assert — should still be false (no PNG), but the current-language path was used
        $this->assertFalse($result);
    }

    /**
     * Language constructor with an explicit language string must attempt
     * to load that language on construction.
     *
     * This covers the `if ($lang <> '')` branch in __construct() (line ~51).
     */
    public function testConstructorWithExplicitLangSetsLanguage(): void
    {
        // Act — construct with explicit language name (no real file needed to prove branch hit)
        $lang = new Language('greek');

        // Assert — the language was recorded even if no file loaded
        $this->assertSame('greek', $lang->currentlang(),
            '__construct() must record the language when one is given explicitly');
    }

    /**
     * Language constructor with an explicit $path must use that path as
     * the language directory instead of the default LANGPATH/ROOT.
     *
     * This covers the `if ($path != null)` branch at the top of __construct()
     * (lines ~41-42).
     */
    public function testConstructorWithCustomPathUsesIt(): void
    {
        // Arrange — create a temp directory (no actual language files needed)
        $tmpDir = sys_get_temp_dir() . '/pramnos_lang_ctor_' . bin2hex(random_bytes(4));
        @mkdir($tmpDir, 0777, true);

        // Act — construct with a custom path; load() will return false but
        // the languagePath property must be set to $tmpDir.
        $lang = new Language('', $tmpDir);

        // Assert — the instance is valid
        $this->assertInstanceOf(Language::class, $lang,
            '__construct() must accept a custom $path argument');

        // Cleanup
        @rmdir($tmpDir);
    }

    /**
     * Language::load() with a custom path must fall back to the 'english'
     * language file if the requested language file does not exist but english
     * does.
     *
     * This covers the elseif (english fallback) branch inside the $path != '' block
     * (lines ~134-138).
     */
    public function testLoadWithCustomPathFallsBackToEnglish(): void
    {
        // Arrange — create temp dir with only an english.php
        $tmpDir  = sys_get_temp_dir() . '/pramnos_lang_test_' . bin2hex(random_bytes(4));
        $langDir = $tmpDir . '/language';
        @mkdir($langDir, 0777, true);
        file_put_contents(
            $langDir . '/english.php',
            "<?php\n\$lang = ['fallback_key' => 'English fallback'];\n"
        );

        // Act — request a non-existent language; should fall back to english
        $result = $this->object->load('nonexistent_xyz', $tmpDir);

        // Assert — english fallback was loaded
        $this->assertTrue($result, 'load() must return true when falling back to english');
        $strings = $this->object->getlang();
        $this->assertArrayHasKey('fallback_key', $strings,
            'load() must merge strings from english fallback');

        // Cleanup
        @unlink($langDir . '/english.php');
        @rmdir($langDir);
        @rmdir($tmpDir);
    }

    /**
     * Language::load() called with an empty string must use the current language
     * (set via _lang) rather than an empty-string file lookup.
     *
     * This covers the `if ($language == '')` branch at line 104 that assigns
     * `$language = $this->_lang` (line 105) — a path no other test exercises.
     */
    public function testLoadWithEmptyLanguageStringUsesCurrentLanguage(): void
    {
        // Arrange — default current language is 'english'
        // Act — pass empty string; load() must substitute the current language internally
        $result = $this->object->load('');

        // Assert — must return a bool without throwing, regardless of whether the file exists
        $this->assertIsBool($result,
            'load("") must return bool after substituting the current language name');
    }

    /**
     * Language::load() with no $path must fall back to english from ROOT/language/
     * if the requested lang file does not exist but english.php does.
     *
     * This covers the elseif ROOT english fallback (line ~120-124).
     * Because ROOT/language may or may not exist in the test environment,
     * we just verify that load() returns a bool without throwing.
     */
    public function testLoadWithNullPathReturnsBoolWithoutThrowing(): void
    {
        // Act — request a non-existent language with no path override;
        // may return true (if ROOT/language/english.php exists) or false
        $result = $this->object->load('zzz_nonexistent_lang_xyzzy');

        // Assert — must always be a bool, never throw
        $this->assertIsBool($result);
    }

    /**
     * Language::getLanguages() must throw when there is no language directory
     * anywhere it looks.
     *
     * "Anywhere it looks" is now three places — LANGPATH, `app/language` and
     * `ROOT/language` — so the throw branch needs all three absent, and the
     * skip below has to check all three rather than the last one.
     */
    public function testGetLanguagesThrowsWhenNoDirectoryExists(): void
    {
        // Arrange — if any of the directories it reads exists, the throw branch
        // is unreachable and asserting on it would be asserting on the
        // environment.
        $candidates = [ROOT . DS . 'app' . DS . 'language', ROOT . DS . 'language'];
        if (defined('LANGPATH')) {
            $candidates[] = LANGPATH;
        }
        foreach ($candidates as $candidate) {
            if (is_dir($candidate)) {
                $this->markTestSkipped(
                    $candidate . ' exists — the throw branch is unreachable here'
                );
            }
        }

        // Assert
        $this->expectException(\Exception::class);
        $this->expectExceptionMessageMatches('/Languages directory does not exist/');

        // Act
        Language::getLanguages();
    }

    /**
     * The English fallback also finds `en.php`.
     *
     * `load()` tries the language asked for, then falls back — and the fallback was the
     * single filename `english`. A project that names its catalogues by ISO code has
     * `en.php` and no `english.php`, so the fallback found nothing, `load()` returned
     * false and **no catalogue was loaded at all**. Every key then rendered as itself,
     * which looks like a site written in English rather than like a language that never
     * loaded: no error, no empty string, nothing to grep for.
     */
    public function testTheEnglishFallbackAlsoFindsAnIsoNamedCatalogue(): void
    {
        // Arrange — an `en.php` and no `english.php`, as init would leave it for a
        // project that named its catalogues by code
        $appLang = ROOT . DS . 'app' . DS . 'language';
        $created = [];
        if (!is_dir($appLang)) {
            @mkdir($appLang, 0777, true);
            $created[] = $appLang;
        }
        $file = $appLang . DS . 'en.php';
        file_put_contents($file, "<?php\n\$lang = ['zzOnlyInEn' => 'found it'];\nreturn \$lang;\n");

        try {
            $language = new Language();

            // Act — a language nobody has a catalogue for
            $loaded = $language->load('zzklingon');

            // Assert
            $this->assertTrue($loaded, 'the fallback must load a catalogue that exists');
            $this->assertSame('found it', $language->_('zzOnlyInEn'));
        } finally {
            @unlink($file);
            foreach ($created as $directory) {
                @rmdir($directory);
            }
        }
    }

    /**
     * getLanguages() looks where load() looks.
     *
     * It used to scan `ROOT/language` and nothing else, while `load()` reads
     * `LANGPATH`, then `app/language`, then `ROOT/language`. On the layout
     * `init` generates — a catalogue in `app/language/` — this method therefore
     * threw "Languages directory does not exist" for a project whose
     * translations were working: `_()` translated happily while anything asking
     * *which* languages existed was told none, so a language picker had nothing
     * to put in it.
     *
     * The reversal that reddens this: scan only `ROOT/language` again, and the
     * greek entry below disappears.
     */
    public function testGetLanguagesFindsTheAppLanguageDirectory(): void
    {
        // Arrange — a catalogue where init puts it, and nowhere else.
        $appLang = ROOT . DS . 'app' . DS . 'language';
        $created = [];
        if (!is_dir($appLang)) {
            @mkdir($appLang, 0777, true);
            $created[] = $appLang;
        }
        $file = $appLang . DS . 'zzgreek.php';
        file_put_contents($file, '<?php $lang = [];');

        try {
            // Act
            $languages = Language::getLanguages();

            // Assert
            $this->assertContains('zzgreek', $languages,
                'a catalogue in app/language/ must be reported');
        } finally {
            @unlink($file);
            foreach ($created as $directory) {
                @rmdir($directory);
            }
        }
    }

    /**
     * A language present in two directories is reported once.
     *
     * Both are scanned and merged, because a project may legitimately have its
     * own strings in `app/language/` and an inherited set in `ROOT/language/`.
     * Merging without deduplicating would put the same language in a picker
     * twice.
     */
    public function testALanguageInTwoDirectoriesIsReportedOnce(): void
    {
        // Arrange
        $appLang  = ROOT . DS . 'app' . DS . 'language';
        $rootLang = ROOT . DS . 'language';
        $created  = [];
        foreach ([$appLang, $rootLang] as $directory) {
            if (!is_dir($directory)) {
                @mkdir($directory, 0777, true);
                $created[] = $directory;
            }
        }
        $files = [$appLang . DS . 'zzboth.php', $rootLang . DS . 'zzboth.php'];
        foreach ($files as $file) {
            file_put_contents($file, '<?php $lang = [];');
        }

        try {
            // Act
            $languages = Language::getLanguages();

            // Assert
            $this->assertSame(
                1,
                count(array_keys($languages, 'zzboth', true)),
                'a language in both directories must appear once'
            );
        } finally {
            foreach ($files as $file) {
                @unlink($file);
            }
            foreach ($created as $directory) {
                @rmdir($directory);
            }
        }
    }

    /**
     * Language::getLanguages() must return an array of language names when the
     * language directory exists.
     */
    public function testGetLanguagesReturnsArrayWhenDirExists(): void
    {
        $dirCreated = false;
        $langDir = ROOT . DIRECTORY_SEPARATOR . 'language';
        if (!is_dir($langDir)) {
            @mkdir($langDir, 0777, true);
            file_put_contents($langDir . DIRECTORY_SEPARATOR . 'english.php', '<?php ');
            $dirCreated = true;
        }

        $langs = Language::getLanguages();
        $this->assertIsArray($langs, 'getLanguages() must return an array');
        $this->assertContains('english', $langs, 'getLanguages() should find english.php');

        if ($dirCreated) {
            @unlink($langDir . DIRECTORY_SEPARATOR . 'english.php');
            @rmdir($langDir);
        }
    }

}

